package cn.panjin.shenxianbms.base.role.dao;

import cn.panjin.shenxianbms.base.role.entity.BaseRole;
import java.util.List;

public interface BaseRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbggenerated
     */
    int insert(BaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbggenerated
     */
    BaseRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbggenerated
     */
    List<BaseRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseRole record);
}