package cn.panjin.shenxianbms.base.role.entity;

import java.io.Serializable;
import java.util.Date;

public class BaseRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.role_code
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.role_type
     *
     * @mbggenerated
     */
    private Byte roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.role_status
     *
     * @mbggenerated
     */
    private Boolean roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.role_description
     *
     * @mbggenerated
     */
    private String roleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.creater_id
     *
     * @mbggenerated
     */
    private Long createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.creater_name
     *
     * @mbggenerated
     */
    private String createrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.id
     *
     * @return the value of base_role.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.id
     *
     * @param id the value for base_role.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.role_code
     *
     * @return the value of base_role.role_code
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.role_code
     *
     * @param roleCode the value for base_role.role_code
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.role_type
     *
     * @return the value of base_role.role_type
     *
     * @mbggenerated
     */
    public Byte getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.role_type
     *
     * @param roleType the value for base_role.role_type
     *
     * @mbggenerated
     */
    public void setRoleType(Byte roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.role_name
     *
     * @return the value of base_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.role_name
     *
     * @param roleName the value for base_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.role_status
     *
     * @return the value of base_role.role_status
     *
     * @mbggenerated
     */
    public Boolean getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.role_status
     *
     * @param roleStatus the value for base_role.role_status
     *
     * @mbggenerated
     */
    public void setRoleStatus(Boolean roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.role_description
     *
     * @return the value of base_role.role_description
     *
     * @mbggenerated
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.role_description
     *
     * @param roleDescription the value for base_role.role_description
     *
     * @mbggenerated
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.creater_id
     *
     * @return the value of base_role.creater_id
     *
     * @mbggenerated
     */
    public Long getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.creater_id
     *
     * @param createrId the value for base_role.creater_id
     *
     * @mbggenerated
     */
    public void setCreaterId(Long createrId) {
        this.createrId = createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.creater_name
     *
     * @return the value of base_role.creater_name
     *
     * @mbggenerated
     */
    public String getCreaterName() {
        return createrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.creater_name
     *
     * @param createrName the value for base_role.creater_name
     *
     * @mbggenerated
     */
    public void setCreaterName(String createrName) {
        this.createrName = createrName == null ? null : createrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.create_time
     *
     * @return the value of base_role.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.create_time
     *
     * @param createTime the value for base_role.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleCode=").append(roleCode);
        sb.append(", roleType=").append(roleType);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleStatus=").append(roleStatus);
        sb.append(", roleDescription=").append(roleDescription);
        sb.append(", createrId=").append(createrId);
        sb.append(", createrName=").append(createrName);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}