server:
  port: 6887

spring:
  datasource:
    url: jdbc:mysql://172.16.0.25:5506/db_resource_center?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ziyuan
    password: ziyuan@962540
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

mybatis:
  mapper-locations: classpath:mybatis/mapping/*DAO.xml