package cn.panjin.shenxianbms.application.multithreading.entity;

import java.io.Serializable;
import java.util.Date;

public class BmsOperationRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.object_id
     *
     * @mbggenerated
     */
    private Long objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.operation_type
     *
     * @mbggenerated
     */
    private Integer operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.operation_content
     *
     * @mbggenerated
     */
    private String operationContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.creater_id
     *
     * @mbggenerated
     */
    private Long createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.creater_org_id
     *
     * @mbggenerated
     */
    private Long createrOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.creater_name
     *
     * @mbggenerated
     */
    private String createrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_operation_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bms_operation_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.id
     *
     * @return the value of bms_operation_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.id
     *
     * @param id the value for bms_operation_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.object_id
     *
     * @return the value of bms_operation_record.object_id
     *
     * @mbggenerated
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.object_id
     *
     * @param objectId the value for bms_operation_record.object_id
     *
     * @mbggenerated
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.operation_type
     *
     * @return the value of bms_operation_record.operation_type
     *
     * @mbggenerated
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.operation_type
     *
     * @param operationType the value for bms_operation_record.operation_type
     *
     * @mbggenerated
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.operation_content
     *
     * @return the value of bms_operation_record.operation_content
     *
     * @mbggenerated
     */
    public String getOperationContent() {
        return operationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.operation_content
     *
     * @param operationContent the value for bms_operation_record.operation_content
     *
     * @mbggenerated
     */
    public void setOperationContent(String operationContent) {
        this.operationContent = operationContent == null ? null : operationContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.creater_id
     *
     * @return the value of bms_operation_record.creater_id
     *
     * @mbggenerated
     */
    public Long getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.creater_id
     *
     * @param createrId the value for bms_operation_record.creater_id
     *
     * @mbggenerated
     */
    public void setCreaterId(Long createrId) {
        this.createrId = createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.creater_org_id
     *
     * @return the value of bms_operation_record.creater_org_id
     *
     * @mbggenerated
     */
    public Long getCreaterOrgId() {
        return createrOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.creater_org_id
     *
     * @param createrOrgId the value for bms_operation_record.creater_org_id
     *
     * @mbggenerated
     */
    public void setCreaterOrgId(Long createrOrgId) {
        this.createrOrgId = createrOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.creater_name
     *
     * @return the value of bms_operation_record.creater_name
     *
     * @mbggenerated
     */
    public String getCreaterName() {
        return createrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.creater_name
     *
     * @param createrName the value for bms_operation_record.creater_name
     *
     * @mbggenerated
     */
    public void setCreaterName(String createrName) {
        this.createrName = createrName == null ? null : createrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_operation_record.create_time
     *
     * @return the value of bms_operation_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_operation_record.create_time
     *
     * @param createTime the value for bms_operation_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_operation_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", objectId=").append(objectId);
        sb.append(", operationType=").append(operationType);
        sb.append(", operationContent=").append(operationContent);
        sb.append(", createrId=").append(createrId);
        sb.append(", createrOrgId=").append(createrOrgId);
        sb.append(", createrName=").append(createrName);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}