package cn.panjin.shenxianbms.base.compiler.entity;

import java.io.Serializable;

public class SpcSourceData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.data_name
     *
     * @mbggenerated
     */
    private String dataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.data_english_name
     *
     * @mbggenerated
     */
    private String dataEnglishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.field_name
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.data_status
     *
     * @mbggenerated
     */
    private Integer dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spc_source_data.data_sql
     *
     * @mbggenerated
     */
    private String dataSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spc_source_data
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.id
     *
     * @return the value of spc_source_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.id
     *
     * @param id the value for spc_source_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.data_name
     *
     * @return the value of spc_source_data.data_name
     *
     * @mbggenerated
     */
    public String getDataName() {
        return dataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.data_name
     *
     * @param dataName the value for spc_source_data.data_name
     *
     * @mbggenerated
     */
    public void setDataName(String dataName) {
        this.dataName = dataName == null ? null : dataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.data_english_name
     *
     * @return the value of spc_source_data.data_english_name
     *
     * @mbggenerated
     */
    public String getDataEnglishName() {
        return dataEnglishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.data_english_name
     *
     * @param dataEnglishName the value for spc_source_data.data_english_name
     *
     * @mbggenerated
     */
    public void setDataEnglishName(String dataEnglishName) {
        this.dataEnglishName = dataEnglishName == null ? null : dataEnglishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.data_type
     *
     * @return the value of spc_source_data.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.data_type
     *
     * @param dataType the value for spc_source_data.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.table_name
     *
     * @return the value of spc_source_data.table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.table_name
     *
     * @param tableName the value for spc_source_data.table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.field_name
     *
     * @return the value of spc_source_data.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.field_name
     *
     * @param fieldName the value for spc_source_data.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.data_status
     *
     * @return the value of spc_source_data.data_status
     *
     * @mbggenerated
     */
    public Integer getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.data_status
     *
     * @param dataStatus the value for spc_source_data.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(Integer dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spc_source_data.data_sql
     *
     * @return the value of spc_source_data.data_sql
     *
     * @mbggenerated
     */
    public String getDataSql() {
        return dataSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spc_source_data.data_sql
     *
     * @param dataSql the value for spc_source_data.data_sql
     *
     * @mbggenerated
     */
    public void setDataSql(String dataSql) {
        this.dataSql = dataSql == null ? null : dataSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spc_source_data
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dataName=").append(dataName);
        sb.append(", dataEnglishName=").append(dataEnglishName);
        sb.append(", dataType=").append(dataType);
        sb.append(", tableName=").append(tableName);
        sb.append(", fieldName=").append(fieldName);
        sb.append(", dataStatus=").append(dataStatus);
        sb.append(", dataSql=").append(dataSql);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}