package cn.panjin.shenxianbms.application.multithreading.dao;

import cn.panjin.shenxianbms.application.multithreading.entity.BmsGoods;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BmsGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_goods
     *
     * @mbggenerated
     */
    int insert(BmsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_goods
     *
     * @mbggenerated
     */
    BmsGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_goods
     *
     * @mbggenerated
     */
    List<BmsGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BmsGoods record);
}